### ISSUE TITLE
Incorrect Amount for Snake, Blokku, E

### ISSUE THREAD

**Issue by rossgalloway** [yam-finance/proposals#10]
https://github.com/yam-finance/proposals/blob/7c0d663fef74fb4a49723406e253f1ae7839d0c1/contracts/2021/12/Proposal21.sol#L83

Payment is for WORK DONE not future work. Snake's pay rate for December was $28,800/year in stables. The number shown here is his new rate and goes into effect NEXT month.

**Comment by rossgalloway** [comment]
The Same holds for Blokku, who should be receiving a rate of $22,500/year in stables for December. Update happens in the next proposal.

Similarly, @ethedev you should still be paying yourself the stables that you earned last month, since your change to 100% YAM goes into effect now and is forward looking.

This confusion here is just an example of how this process is broken and incredibly hard to understand.

**Comment by snake-poison** [comment]
> The Same holds for Blokku, who should be receiving a rate of $22,500/year in stables for December. Update happens in the next proposal.
> 
> 
> 
> Similarly, @ethedev you should still be paying yourself the stables that you earned last month, since your change to 100% YAM goes into effect now and is forward looking.
> 
> 
> 
> This confusion here is just an example of how this process is broken and incredibly hard to understand.

If the goal is to get this asap, could you please just recommend the changes that need to be made? As in change the amount to X usd for Y contributor. 

This is the current process (having multiple review) so I'm not sure how pointing out that a mistake was made demonstrates a broken process.

**Comment by ethedev** [comment]
Good noticing, Blokku and Snake are updated, though for my comp it is correct as is, as i received that already previously.
