### ISSUE TITLE
Please confirm logic

### ISSUE THREAD

**Issue by rossgalloway** [yam-finance/proposals#20]
Can you confirm the logic here:

This code moves all our USDC into this contract
https://github.com/yam-finance/proposals/blob/169d1fa74dd8f2aab4d66de4dcacf831e0922dd2/contracts/2022/02/Proposal23.sol#L135-L138

This code moves all our yUSDC2 (the old version) into this contract
https://github.com/yam-finance/proposals/blob/169d1fa74dd8f2aab4d66de4dcacf831e0922dd2/contracts/2022/02/Proposal23.sol#L140-L144

This code withdraws the yUSDC2 (old version) to USDC.
https://github.com/yam-finance/proposals/blob/169d1fa74dd8f2aab4d66de4dcacf831e0922dd2/contracts/2022/02/Proposal23.sol#L145

This line then sends 100,000 USDC back to the treasury.
https://github.com/yam-finance/proposals/blob/169d1fa74dd8f2aab4d66de4dcacf831e0922dd2/contracts/2022/02/Proposal23.sol#L150

The contract then pays people

This code then deposits all the remaining USDC into yvUSDC (the new version) and sends it back to the treasury.
https://github.com/yam-finance/proposals/blob/169d1fa74dd8f2aab4d66de4dcacf831e0922dd2/contracts/2022/02/Proposal23.sol#L184-L186

This is how I understand the contract working. Please confirm if that is correct.

Either way, I have a few comments:
1. Why not also pull in the yUSD, unwrap to USDC and move that to the new yvUSDC vault? Or just unwrap it to USDC and use that as part of the buffer to pay contributors.
2. Variable naming for this is confusing. yUSDCv2 is the old version and yUSDC is the new version?
3. Would love to see more comments to explain what we are doing.

**Comment by ethedev** [comment]
correct

1. all the yUSD/stable related tokens in the treasury are being moved into the new yUSDC keeping 100k in USDC tokens for a 2 month pay buffer
2. yes
3. sure
