### ISSUE TITLE
Add VDM to contributors paid

### ISSUE THREAD

**Issue by rossgalloway** [yam-finance/proposals#21]
https://github.com/yam-finance/proposals/blob/169d1fa74dd8f2aab4d66de4dcacf831e0922dd2/contracts/2022/02/Proposal23.sol#L152

VDM submitted a compensation request and should be included in this proposal
https://forum.yam.finance/t/2022-03-01-vdm-contribution-compensation-request/1627

**Comment by ethedev** [comment]
very late now, will be adding into the next one

**Comment by rossgalloway** [comment]
this is unacceptable
