### ISSUE TITLE
How do we know this picks USDC?

### ISSUE THREAD

**Issue by rossgalloway** [yam-finance/proposals#24]
https://github.com/yam-finance/proposals/blob/ef05f7b20512ab00b45828d37ddadce21a96f741/contracts/2022/03/Proposal24.sol#L22-L28

https://github.com/yam-finance/proposals/blob/ef05f7b20512ab00b45828d37ddadce21a96f741/contracts/2022/03/Proposal24.sol#L104

I may just have missed it, but I don't see anything in this function and it's definition that says what token gets paid out. Maybe not an issue but I figured I would ask.

Is the variable name spelled right in line 26 (uamount)?

**Comment by ethedev** [comment]
> I may just have missed it, but I don't see anything in this function and it's definition that says what token gets paid out. Maybe not an issue but I figured I would ask.

USDC comes from `i` as `1`.

> Is the variable name spelled right in line 26 (uamount)?

Yes thats correct.
