### ISSUE TITLE
Proposal 20 - Nate's Pay

### ISSUE THREAD

**Issue by rossgalloway** [yam-finance/proposals#7]
https://github.com/yam-finance/proposals/blob/4f7eec8c412a711e036ca9c4abc03d3184ce7e40/contracts/2021/Proposal20.sol#L96

@ethedev have you had further conversations with Nate about this? Per the discussion where nate first announced that he would be stepping away he mentioned that we wanted to stop his stablecoin payments immediately. That was in early october, so would mean that if we follow that we wouldn't pay him in this proposal (covering october and november).

At the bottom of the proposal, (line 165) nates stream is closed. Are we fully parting ways or just stopping until things get re-negotiated?

**Comment by ethedev** [comment]
> At the bottom of the proposal, (line 165) nates stream is closed. Are we fully parting ways or just stopping until things get re-negotiated?

thats a week of october pay which was last, but yes for the moment we are pausing things until we have an updated proposal for him

**Comment by ethedev** [comment]
> At the bottom of the proposal, (line 165) nates stream is closed. Are we fully parting ways or just stopping until things get re-negotiated?

thats a week of october pay which was last, and for the moment we are pausing things until we have an updated proposal for him

**Comment by rossgalloway** [comment]
ok
