### ISSUE TITLE
Proposal 20 - Mistake in VDM's Previous Pay

### ISSUE THREAD

**Issue by rossgalloway** [yam-finance/proposals#9]
https://github.com/yam-finance/proposals/blob/4f7eec8c412a711e036ca9c4abc03d3184ce7e40/contracts/2021/Proposal20.sol#L102

As I reviewed the last proposal, I discovered that we underpaid VDM for the month of September.  The snapshot proposal that was approved here: https://snapshot.org/#/yam.eth/proposal/QmTH6QZnNxrRGhMxyEbwiE7VFPCTz1TYGnDHRJghnvgMR9 was for future months. In that proposal, VDM was approved for move to half time with half pay for the month of October. In the last on chain proposal that Nate wrote, we paid VDM `42000/12` or $3500, when he should have been paid $7000 (84000/2) because that proposal was to pay for work done in the _previous month_. https://github.com/yam-finance/proposals/blob/4d22666969d25a69ae0f1d06f115d19d0e027583/contracts/proposals/proposal_19/Proposal19.sol#L99

In order to fix this now, we should pay VDM the 3500 USDC that we owe him for september, and then also the 3500 USDC we owe him for his part time work in October. We are then not paying him stables for November on, but keeping his stream open until we ratify his new compensation plan.

**Comment by ethedev** [comment]
updated
